### ISSUE TITLE
Initial Roadmap

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-pivottable#1]
- [x] port over `$.pivotUtilities` and specs
- [x] basic `TableRenderer`
- [x] basic Storybook-powered website running at https://react-pivottable.js.org
- [x] basic `PivotTable` component
- [x] get `eslint` going and figure out a decent React formatting scheme
- [x] `propTypes`
- [x] basic dumb `PivotTableUI` component (just drag'n'drop and aggregator selection, no filter) plus smart wrapper (using https://github.com/RubaXa/Sortable ? )
- [x] filter menu on `PivotTableUI` MVP
- [x] pull together a ReadMe with a project charter
- [ ] do a first NPM release to populate the entry a bit more
- [ ] Heatmaps
- [ ] Plotly.js-react renderer!
- [ ] sorters
- [ ] row/col order
- [ ] derived attributes?
- [ ] hidden attributes
- [ ] fancier filter menu: select all/none/only, include mode, fancy filter, sorter-aware?
- [ ] localization
- [ ] get some badges, a CI setup for tests, some test coverage
- [ ] Dash component (https://plot.ly/dash/plugins)
- [ ] some React-level tests with `jest`

**Comment by nirvana-msu** [comment]
This is awesome! I'm really looking forward to a Dash component!

What would make it even more useful for me is the ability to do server-side aggregations. I know you've decided not to implement this in the jQuery version, but since it gets a major re-vamp, maybe there's room to re-consider?

I did leave a comment in the original jQuery issue tracker: https://github.com/nicolaskruchten/pivottable/issues/150

It would be perfect for Dash. If an interface which I described in that other issue existed, we could just hook up python callback to return aggregated data (given all the groupings and filters), and other callbacks to return unique values for filters.

**Comment by nicolaskruchten** [comment]
@nirvana-msu I'm glad you're excited about this project! Server-side integration is something we're keeping in mind but it's not part of the roadmap just yet, so I can't commit to anything. Most likely if we do support server-side aggregation it will be Dash-specific, not general-purpose, at least to begin with.

**Comment by nirvana-msu** [comment]
Dash-specific integration would suit me as I mostly use Dash. But I guess, if designed correctly, it's not any  harder to make it server-side -agnostic. Anyways, I'm not an expert in React (or js for that matter) so cannot help much, apart from relaying my experience in doing the same thing in java / Jide.

**Comment by teimurjan** [comment]
Hello, when are you going to add localization?

**Comment by nicolaskruchten** [comment]
Hi there!

I'm waiting for the API to fully stabilize, but it's high on my priority list!

**Comment by rjst** [comment]
Hi,

This looks great :)

I'm wondering if there's a way to see the underlying data of a chart component ? (for example, clicking on a bar and seeing a table of records that make up that bar)

thanks,
Ricardo

**Comment by nicolaskruchten** [comment]
@rjst glad you like it! unfortunately that's not supported at the moment but I would accept a PR for it :)

PS: please create new issues rather than commenting on this one, as otherwise the notifications will get out of control here ;)

**Comment by debugpoint136** [comment]
Is click or double-click on a cell supported? 
I am looking for this feature `https://pivottable.js.org/examples/mps_prepop.html` in the React ported version. Many thanks!

**Comment by nicolaskruchten** [comment]
@debugpoint136 it's not supported yet but it should be relatively easy to submit a PR if you need this :)

**Comment by nicolaskruchten** [comment]
I'm locking this issue now... Please create new issues if you have roadmap questions :)
